/**
 * icons.ts — Centralised icon abstraction over @heroicons/react
 *
 * Usage:
 *   import { getIcon, ICON_LIST } from "@/lib/icons"
 *   const Icon = getIcon("Star")  // → StarIcon (outline, 24px)
 */

import type { ComponentType, SVGProps } from "react";

// ─── Outline (primary variant) ───────────────────────────────────────────────
export {
    AcademicCapIcon,
    AdjustmentsHorizontalIcon,
    ArchiveBoxIcon,
    ArrowDownIcon,
    ArrowLeftIcon,
    ArrowRightIcon,
    ArrowsPointingOutIcon,
    ArrowTopRightOnSquareIcon,
    ArrowUpIcon,
    ArrowUpTrayIcon,
    AtSymbolIcon,
    BanknotesIcon,
    Bars3Icon,
    BellIcon,
    BoltIcon,
    BookmarkIcon,
    BookOpenIcon,
    BriefcaseIcon,
    BuildingLibraryIcon,
    BuildingOffice2Icon,
    CalendarIcon,
    CameraIcon,
    ChartBarIcon,
    ChartPieIcon,
    ChatBubbleLeftIcon,
    CheckCircleIcon,
    CheckIcon,
    ChevronDownIcon,
    ChevronRightIcon,
    ClipboardIcon,
    ClockIcon,
    CloudIcon,
    CodeBracketIcon,
    CogIcon,
    CommandLineIcon,
    ComputerDesktopIcon,
    CreditCardIcon,
    DevicePhoneMobileIcon,
    DocumentIcon,
    DocumentTextIcon,
    EllipsisHorizontalIcon,
    EnvelopeIcon,
    ExclamationCircleIcon,
    ExclamationTriangleIcon,
    EyeIcon,
    EyeSlashIcon,
    FaceSmileIcon,
    FilmIcon,
    FingerPrintIcon,
    FireIcon,
    FlagIcon,
    FolderIcon,
    GiftIcon,
    GlobeAltIcon,
    GlobeAmericasIcon,
    HandThumbUpIcon,
    HashtagIcon,
    HeartIcon,
    HomeIcon,
    InboxIcon,
    InformationCircleIcon,
    KeyIcon,
    LightBulbIcon,
    LinkIcon,
    LockClosedIcon,
    LockOpenIcon,
    MagnifyingGlassIcon,
    MapIcon,
    MapPinIcon,
    MegaphoneIcon,
    MicrophoneIcon,
    MinusCircleIcon,
    MoonIcon,
    MusicalNoteIcon,
    NewspaperIcon,
    PaperAirplaneIcon,
    PaperClipIcon,
    PauseIcon,
    PencilIcon,
    PhoneIcon,
    PhotoIcon,
    PlayIcon,
    PlusCircleIcon,
    PlusIcon,
    PrinterIcon,
    PuzzlePieceIcon,
    QrCodeIcon,
    QuestionMarkCircleIcon,
    RocketLaunchIcon,
    ScaleIcon,
    ServerIcon,
    ShareIcon,
    ShieldCheckIcon,
    ShoppingBagIcon,
    ShoppingCartIcon,
    SignalIcon,
    SparklesIcon,
    SpeakerWaveIcon,
    Square2StackIcon,
    Squares2X2Icon,
    StarIcon,
    SunIcon,
    SwatchIcon,
    TableCellsIcon,
    TagIcon,
    TrashIcon,
    TrophyIcon,
    TruckIcon,
    UserCircleIcon,
    UserGroupIcon,
    UserIcon,
    UsersIcon,
    VideoCameraIcon,
    WifiIcon,
    WrenchIcon,
    XCircleIcon,
    XMarkIcon,
} from "@heroicons/react/24/outline";

// ─── Solid (filled variant for accent / block icons) ─────────────────────────
export {
    StarIcon as StarSolidIcon,
    HeartIcon as HeartSolidIcon,
    BoltIcon as BoltSolidIcon,
    CheckCircleIcon as CheckCircleSolidIcon,
    ShieldCheckIcon as ShieldCheckSolidIcon,
    FireIcon as FireSolidIcon,
    SparklesIcon as SparklesSolidIcon,
    RocketLaunchIcon as RocketLaunchSolidIcon,
    GlobeAltIcon as GlobeAltSolidIcon,
} from "@heroicons/react/24/solid";

// ─── Icon type ────────────────────────────────────────────────────────────────

// ─── Curated icon list for the icon picker ───────────────────────────────────
// Format: { name: string (used for storage), label: string (human readable) }
import * as OutlineIcons from "@heroicons/react/24/outline";
import type { HeroIcon, IconEntry } from "@/@Types";

// Map Heroicons names → friendly display labels and picker name (no "Icon" suffix)
const HEROICONS_MAP: Record<string, string> = {
    AcademicCapIcon: "Academic Cap",
    AdjustmentsHorizontalIcon: "Adjustments",
    ArchiveBoxIcon: "Archive",
    ArrowDownIcon: "Arrow Down",
    ArrowLeftIcon: "Arrow Left",
    ArrowRightIcon: "Arrow Right",
    ArrowsPointingOutIcon: "Expand",
    ArrowTopRightOnSquareIcon: "External Link",
    ArrowUpIcon: "Arrow Up",
    ArrowUpTrayIcon: "Upload",
    AtSymbolIcon: "@ Symbol",
    BanknotesIcon: "Banknotes",
    Bars3Icon: "Menu",
    BellIcon: "Bell",
    BoltIcon: "Bolt / Zap",
    BookmarkIcon: "Bookmark",
    BookOpenIcon: "Book",
    BriefcaseIcon: "Briefcase",
    BuildingLibraryIcon: "Library",
    BuildingOffice2Icon: "Office",
    CalendarIcon: "Calendar",
    CameraIcon: "Camera",
    ChartBarIcon: "Chart Bar",
    ChartPieIcon: "Chart Pie",
    ChatBubbleLeftIcon: "Chat",
    CheckCircleIcon: "Check Circle",
    CheckIcon: "Check",
    ChevronDownIcon: "Chevron Down",
    ChevronRightIcon: "Chevron Right",
    ClipboardIcon: "Clipboard",
    ClockIcon: "Clock",
    CloudIcon: "Cloud",
    CodeBracketIcon: "Code",
    CogIcon: "Settings",
    CommandLineIcon: "Terminal",
    ComputerDesktopIcon: "Desktop",
    CreditCardIcon: "Credit Card",
    DevicePhoneMobileIcon: "Mobile",
    DocumentIcon: "Document",
    DocumentTextIcon: "Document Text",
    EllipsisHorizontalIcon: "More",
    EnvelopeIcon: "Email",
    ExclamationCircleIcon: "Warning Circle",
    ExclamationTriangleIcon: "Warning Triangle",
    EyeIcon: "Eye",
    EyeSlashIcon: "Eye Off",
    FaceSmileIcon: "Smile",
    FilmIcon: "Film",
    FingerPrintIcon: "Fingerprint",
    FireIcon: "Fire",
    FlagIcon: "Flag",
    FolderIcon: "Folder",
    GiftIcon: "Gift",
    GlobeAltIcon: "Globe",
    GlobeAmericasIcon: "Globe Americas",
    HandThumbUpIcon: "Like",
    HashtagIcon: "Hashtag",
    HeartIcon: "Heart",
    HomeIcon: "Home",
    InboxIcon: "Inbox",
    InformationCircleIcon: "Info",
    KeyIcon: "Key",
    LightBulbIcon: "Light Bulb",
    LinkIcon: "Link",
    LockClosedIcon: "Lock",
    LockOpenIcon: "Unlock",
    MagnifyingGlassIcon: "Search",
    MapIcon: "Map",
    MapPinIcon: "Location",
    MegaphoneIcon: "Megaphone",
    MicrophoneIcon: "Microphone",
    MinusCircleIcon: "Minus",
    MoonIcon: "Moon",
    MusicalNoteIcon: "Music",
    NewspaperIcon: "News",
    PaperAirplaneIcon: "Send",
    PaperClipIcon: "Attachment",
    PauseIcon: "Pause",
    PencilIcon: "Pencil / Edit",
    PhoneIcon: "Phone",
    PhotoIcon: "Photo",
    PlayIcon: "Play",
    PlusCircleIcon: "Plus Circle",
    PlusIcon: "Plus",
    PrinterIcon: "Printer",
    PuzzlePieceIcon: "Puzzle",
    QrCodeIcon: "QR Code",
    QuestionMarkCircleIcon: "Help",
    RocketLaunchIcon: "Rocket",
    ScaleIcon: "Scale / Balance",
    ServerIcon: "Server",
    ShareIcon: "Share",
    ShieldCheckIcon: "Shield",
    ShoppingBagIcon: "Shopping Bag",
    ShoppingCartIcon: "Cart",
    SignalIcon: "Signal",
    SparklesIcon: "Sparkles",
    SpeakerWaveIcon: "Speaker",
    Square2StackIcon: "Stack",
    Squares2X2Icon: "Grid",
    StarIcon: "Star",
    SunIcon: "Sun",
    SwatchIcon: "Palette",
    TableCellsIcon: "Table",
    TagIcon: "Tag",
    TrashIcon: "Trash",
    TrophyIcon: "Trophy",
    TruckIcon: "Truck",
    UserCircleIcon: "User Circle",
    UserGroupIcon: "User Group",
    UserIcon: "User",
    UsersIcon: "Users",
    VideoCameraIcon: "Video",
    WifiIcon: "WiFi",
    WrenchIcon: "Wrench",
    XCircleIcon: "X Circle",
    XMarkIcon: "Close",
};

// Build the ICON_LIST from the map
export const ICON_LIST: IconEntry[] = Object.entries(HEROICONS_MAP)
    .map(([heroName, label]) => {
        const Icon = (OutlineIcons as Record<string, HeroIcon>)[heroName];
        if (!Icon) return null;
        // Picker name: strip trailing "Icon" → "StarIcon" → "Star"
        const name = heroName.endsWith("Icon") ? heroName.slice(0, -4) : heroName;
        return { name, label, Icon };
    })
    .filter(Boolean) as IconEntry[];

/**
 * getIcon(name: string): HeroIcon | null
 *
 * Given a picker name like "Star", returns StarIcon from @heroicons/react/24/outline.
 * Falls back to attempting "name + Icon" lookup.
 */
export function getIcon(name: string): HeroIcon | null {
    if (!name) return null;
    // Try direct lookup: "StarIcon"
    let icon = (OutlineIcons as Record<string, HeroIcon>)[name];
    if (icon) return icon;
    // Try appending Icon suffix: "Star" → "StarIcon"
    icon = (OutlineIcons as Record<string, HeroIcon>)[`${name}Icon`];
    if (icon) return icon;
    return null;
}

/**
 * Legacy Lucide name → Heroicons name mapping
 * Used for migrating stored icon names in existing page content
 */
export const LUCIDE_TO_HERO: Record<string, string> = {
    Zap: "Bolt",
    Star: "Star",
    Shield: "ShieldCheck",
    CheckCircle: "CheckCircle",
    Layout: "Squares2X2",
    LayoutPanelTop: "Squares2X2",
    LayoutList: "DocumentText",
    LayoutDashboard: "Squares2X2",
    LayoutTemplate: "Squares2X2",
    Columns2: "Square2Stack",
    PanelBottom: "DocumentText",
    DragHandleDots2: "EllipsisHorizontal",
    GripVertical: "EllipsisHorizontal",
    Plus: "Plus",
    X: "XMark",
    Menu: "Bars3",
    Moon: "Moon",
    Sun: "Sun",
    Monitor: "ComputerDesktop",
    User: "User",
    LogOut: "ArrowLeft",
    FileText: "DocumentText",
    Globe: "GlobeAlt",
    Clock: "Clock",
    MoreHorizontal: "EllipsisHorizontal",
    Edit3: "Pencil",
    Copy: "Clipboard",
    Trash2: "Trash",
    ExternalLink: "ArrowTopRightOnSquare",
    ArrowRight: "ArrowRight",
    ArrowUp: "ArrowUp",
    Play: "Play",
    Sparkles: "Sparkles",
    Eye: "Eye",
    EyeOff: "EyeSlash",
    Loader2: "ArrowRight",
    Twitter: "GlobeAlt",
    Github: "CodeBracket",
    Linkedin: "GlobeAlt",
    Mail: "Envelope",
    Heart: "Heart",
    Image: "Photo",
    ImageIcon: "Photo",
    BoxSelect: "Square2Stack",
    Pipette: "Swatch",
    Check: "Check",
    ChevronDown: "ChevronDown",
    ChevronRight: "ChevronRight",
    Sparkle: "Sparkles",
    MousePointerClick: "CursorArrowRays",
    Minus: "MinusCircle",
    Video: "VideoCamera",
    Users: "Users",
    Mail2: "Envelope",
    Square: "Square2Stack",
    Type: "DocumentText",
    BoxSelectIcon: "Square2Stack",
};
